name: Recru_It

on: # [push]
  schedule:
    - cron: '07 17 * * *'	# 매일 02:07 (UTC+9) [UTC기준 매일 17:07]
    # - cron: '28 17 * * 1,3,5'	# 화, 목, 토 02:28 (UTC+9) [UTC기준 월, 수, 금 17:28]
    # - cron: '55 23 31 2 4'	# 실행되지 않을 것

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Defendency
      run: |
        sudo apt-get install python3 python3-dev python3-pip libxml2-dev libxslt1-dev zlib1g-dev libffi-dev libssl-dev
        python3 -m pip install -U pyOpenSSL cryptography
    - name: Requirements
      run: |
        hostname -I
        pwd
        ls -al
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Execution
      run: |
        pwd
        ls -al

        if [ -f recru_result.json ]; then rm -f recru_result.json; fi
        scrapy crawl recru_it -o recru_result.json -t json

        LEN=$(cat recru_result.json | wc -m)
        if [ "${LEN}" -gt 500 ]; then
          echo "Grater than 500"
          cp -fp recru_result.json ../jobInfo.json
        else
          echo "Less than 500"
          echo "Do nothing"
        fi
      working-directory: ./recru_it
    
    - name: Commit files
      run: |
        git config --local user.email "hjpyooo@gmail.com"
        git config --local user.name "Jay"
        git add .
        git commit -m "Recru_It" --amend
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        force_with_lease: true
